### ISSUE TITLE
"getValue" on an undefined value

### ISSUE THREAD

**Issue by rijvirajib** [struan/webservice-validator-html-w3c#2]
Can't call method "getValue" on an undefined value at /usr/local/share/perl5/WebService/Validator/HTML/W3C.pm line 352, <DATA> line 1.\t\tStack: [/usr/local/share/perl5/WebService/Validator/HTML/W3C.pm:352]

This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi .

Works on most URLs but fails on specific ones.

foreach my $error ( @{$v->errors} ) { } => is where it fails in my own code

**Comment by struan** [comment]
You don't happen to have an example of a URL this fails on?

Thanks

**Comment by rijvirajib** [comment]
http://parkinsonsclinic.com

**Comment by rijvirajib** [comment]
From what I can tell, on line 18 of their HTML output, they have text there that shouldn't be there - it might be breaking the parser, not sure though.
